name: foodtruckz
description: Displays foodtrucks in Nuremberg for the current user location
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # modules
  core:
    path: modules/libraries/core
  foodtruck_overview:
    path: modules/features/foodtruck_overview
  foodtruck_details:
    path: modules/features/foodtruck_details


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.0"

flutter:
  uses-material-design: true