name: core
description: Contains all dependencies and shared code

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # logging
  fimber: ^0.6.6

  # data flow
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # data classes
  equatable: ^2.0.5
  json_annotation: ^4.8.0

  # network
  dio: ^5.0.2
  retrofit: ^4.0.1

  # location
  location: ^4.4.0

  # collection
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

  # Code generation
  json_serializable: ^6.6.1
  analyzer: ^5.7.1
  build_verify: ^3.1.0
  retrofit_generator: ^6.0.0+1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true